# Generated by Django 4.2.6 on 2024-02-06 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_questiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
