# Generated by Django 4.2.6 on 2024-02-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_questiondata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondata',
            name='admin_comment',
            field=models.CharField(default='Nothing', max_length=200),
        ),
    ]
