# Generated by Django 4.2.6 on 2024-02-06 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_questiondata_admin_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usesignup',
            name='lastname',
        ),
        migrations.AddField(
            model_name='usesignup',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
